### PR TITLE
Build to UMD module and transpile down to ES5

### PR DESCRIPTION
**Pull request by afrith**
This PR adds Webpack configuration to the client library build process that does two things.
- Builds to a UMD module, which makes it easier to import the library in various environments.
- Transpiles the ES6+ code features (async, arrow functions, etc.) down to ES5 so the code will run in older browsers.

### CODE REVIEW

**Review by djhi — COMMENTED** [review]
Thanks for working on this. I'd rather have two outputs if possible though (umd and esm).

**Comment by afrith** [comment]
Makes sense, I've updated it so that the existing ESM build remains at `dist/main.js` and the UMD is built at `dist/main.umd.js`. I'm not sure if there's anything in `package.json` that would also need to be changed for this?

**Comment by djhi** [comment]
> I'm not sure if there's anything in package.json that would also need to be changed for this?

There is.

The esm build should be referenced under a `module` key instead of `main`.
The umd module should the one in `main`

**Review by Kmaschta — APPROVED** [review]
It's ok, I'll do the publication stuff :°+1
Thanks for the PR!

**Pull request merged**
